/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cap05.resueltos.Prestamo;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.event.*;


/**
 *
 * @author ᴊɪᴍʀᴏᴅ
 */
public class Prestamo extends javax.swing.JFrame {
        private javax.swing.JTable jtablaPrestamo;
    private javax.swing.JTable jtablaCabTabla;

        
   

       
    private double credito;
    private int periodoMax, periodoMin;
    private double interesMin, interesMax;
    private double incremento;
    
    private int tiposIntrs = 18;  // Número de filas por omisión
    private int añosMeses = 4;    // Número de columnas por omisión
    private boolean tablaPagos = true;
    private double pagoMensual = 0.0;
    
    private class CModeloTablaPrestamo extends javax.swing.table.AbstractTableModel
{
    Object dato[][];
    String cabecera[];
    boolean editColum[];

    CModeloTablaPrestamo(int filas, int columnas)
    {
        dato = new Object[filas][columnas];
        cabecera = new String[columnas];
        editColum = new boolean[columnas];
        for (int c = 0; c < columnas; c++)
        {
            cabecera[c] = "Columna " + c;
            if (c != 0) editColum[c] = true;
        }
    }

    public int getColumnCount() { return cabecera.length; }
    public int getRowCount() { return dato.length; }
    public String getColumnName(int col) { return cabecera[col]; }
    public Object getValueAt(int fila, int col) { return dato[fila][col]; }
    public void setValueAt(Object obj, int fila, int col) { dato[fila][col] = obj; }
    public boolean isCellEditable(int row, int col) { return editColum[col]; }
}



    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Prestamo.class.getName());

    /**
     * Creates new form Prestamo
     */
    public Prestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jftCredito = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jftPeriodoMax = new javax.swing.JTextField();
        jftPeriodoMin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jftInteresMax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jftInteresMin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbIncremento = new javax.swing.JComboBox<>();
        jbtCalculoPagos = new javax.swing.JButton();
        jbtCalculoAmort = new javax.swing.JButton();
        jscrollPanel = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiInstrucciones = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiMeses = new javax.swing.JRadioButtonMenuItem();
        jmiAños = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Crédito:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        getContentPane().add(jftCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Años del préstamo"));

        jLabel2.setText("Máximo:");

        jLabel3.setText("Mínimo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftPeriodoMin, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jftPeriodoMax))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jftPeriodoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jftPeriodoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos de interés"));

        jLabel4.setText(" % máximo:");

        jLabel5.setText("% mínimo:");

        jLabel6.setText("Incremento:");

        jcbIncremento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.10", "0.25", "0.50", "1.00", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftInteresMax, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftInteresMin)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jftInteresMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jftInteresMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 150));

        jbtCalculoPagos.setText("Pagos");
        jbtCalculoPagos.addActionListener(this::jbtCalculoPagosActionPerformed);
        getContentPane().add(jbtCalculoPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 170, -1));

        jbtCalculoAmort.setText("Amortización");
        jbtCalculoAmort.setEnabled(false);
        jbtCalculoAmort.addActionListener(this::jbtCalculoAmortActionPerformed);
        getContentPane().add(jbtCalculoAmort, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscrollPanel.setViewportView(jTable1);

        getContentPane().add(jscrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 300, 370));

        jMenu1.setText("Opciones");

        jmiInstrucciones.setText("Instrucciones");
        jmiInstrucciones.addActionListener(this::jmiInstruccionesActionPerformed);
        jMenu1.add(jmiInstrucciones);

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(this::jmiSalirActionPerformed);
        jMenu1.add(jmiSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Préstamo en...");

        jmiMeses.setSelected(true);
        jmiMeses.setText("Meses");
        jmiMeses.addActionListener(this::jmiMesesActionPerformed);
        jMenu2.add(jmiMeses);

        jmiAños.setSelected(true);
        jmiAños.setText("Años");
        jmiAños.addActionListener(this::jmiAñosActionPerformed);
        jMenu2.add(jmiAños);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jmiAcercaDe.setText("Acerca de Préstamo...");
        jmiAcercaDe.addActionListener(this::jmiAcercaDeActionPerformed);
        jMenu3.add(jmiAcercaDe);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAcercaDeActionPerformed
             javax.swing.JOptionPane.showMessageDialog(null,
            "Aplicación Préstamo, Versión 1.0\n" +
            "Copyright (c) Fco. Javier Ceballos, 2014",
            "Acerca de...", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmiAcercaDeActionPerformed

    private void jmiAñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAñosActionPerformed
    jmiMeses.setSelected(false);
    jmiAños.setEnabled(false);
    jmiMeses.setEnabled(true);
    jPanel1.setBorder(new javax.swing.border.TitledBorder("Años del préstamo"));
    jPanel1.repaint();

    }//GEN-LAST:event_jmiAñosActionPerformed

    private void jmiMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMesesActionPerformed
    jmiAños.setSelected(false);
    jmiMeses.setEnabled(false);
    jmiAños.setEnabled(true);
    jPanel1.setBorder(new javax.swing.border.TitledBorder("Meses del préstamo"));
    jPanel1.repaint();

    }//GEN-LAST:event_jmiMesesActionPerformed

    private void jmiInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInstruccionesActionPerformed
     String mensaje;
    mensaje = "Introduzca el crédito, la duración del préstamo y el tipo\n";
    mensaje += "de interés. Pulse el botón [Pagos] para visualizar\n";
    mensaje += "los pagos mensuales en la rejilla.\n\n";
    mensaje += "Elija un pago mensual y pulse el botón [Amortización]\n";
    mensaje += "para visualizar el plan de amortización para el interés\n";
    mensaje += "y períodos correspondientes al pago elegido.\n\n";
    mensaje += "Para copiar datos en el portapapeles, seleccione las celdas\n";
    mensaje += "que desee y pulse las teclas Ctrl+c.\n";
    javax.swing.JOptionPane.showMessageDialog(
            null, mensaje, "Instrucciones",
            javax.swing.JOptionPane.INFORMATION_MESSAGE) ;

    }//GEN-LAST:event_jmiInstruccionesActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
          System.exit(0);

    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jbtCalculoPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalculoPagosActionPerformed
                                           
    // Actualizar las variables con los valores de los controles
    try
    {
        credito = Double.parseDouble(jftCredito.getText());
        periodoMin = Integer.parseInt(jftPeriodoMin.getText());
        periodoMax = Integer.parseInt(jftPeriodoMax.getText());
        interesMin = Double.parseDouble(jftInteresMin.getText());
        interesMax = Double.parseDouble(jftInteresMax.getText());
        incremento = Double.parseDouble((String)jcbIncremento.getSelectedItem());

        // Comprobar que los datos son válidos
        if (credito <= 0 ||
            periodoMin <= 0 || periodoMax <= 0 || periodoMax < periodoMin ||
            interesMin < 0 || interesMax < 0 || interesMax < interesMin)
            throw new NumberFormatException();
    }
    catch (NumberFormatException e)
    {
        javax.swing.JOptionPane.showMessageDialog(
                null, "Datos no válidos",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Calcular el nº de tipos de interés y de períodos
    tiposIntrs = (int)((interesMax - interesMin)/incremento) + 1;
    añosMeses = (periodoMax - periodoMin) + 1;

    // Tamaño mínimo de la tabla: los valores iniciales
    int filas = tiposIntrs, cols = añosMeses;
    if (tiposIntrs < 18) filas = 18;
    if (añosMeses < 4) cols = 4;
    javax.swing.table.TableColumnModel modeloColums = new javax.swing.table.DefaultTableColumnModel();
       jtablaPrestamo = jTable1;
    jtablaCabTabla = jTable1;



    // Crear la tabla
    initTabla(filas, cols + 1);

    // Almacenar en la columna 0 los tipos de interés
    jtablaCabTabla.setValueAt(AlinDer("##0.00", interesMin)+"%", 0, 0);
    for (int fila = 1; fila < tiposIntrs; ++fila)
        jtablaCabTabla.setValueAt(AlinDer("##0.00",
                interesMin + incremento * fila)+"%", fila, 0);

    // Almacenar en la fila 0 las distintas duraciones del préstamo
    javax.swing.table.TableColumn colum = null;
    String per = " años";
    if (jmiAños.isEnabled()) per = " meses";
    for (int columna = 0; columna < añosMeses; ++columna)
    {
        colum = jtablaPrestamo.getColumnModel().getColumn(columna);
        colum.setHeaderValue((periodoMin + columna) + per);
    }

    // Los períodos ¿en qué vienen dados? ¿En años o en meses?
    int P = 0;
    if (!jmiAños.isEnabled())
        P = 12; // son años
    else
        P = 1; // son meses

    // Calcular pagos
    double interes = 0.0, pagoMensualLocal = 0.0;
    int meses;
    for (int fila = 0; fila < tiposIntrs; ++fila)
    {
        // Obtener el tipo de interés de la fila actual
        String sinteres = jtablaCabTabla.getValueAt(fila, 0).toString();
        sinteres = sinteres.substring(0, sinteres.indexOf('%'));
        sinteres = sinteres.replace(',', '.');
        interes = Double.parseDouble(sinteres) / 100 / 12;
        
        // Calcular los pagos para este tipo de interés
        for (int columna = 0; columna < añosMeses; ++columna)
        {
            // Obtener la duración del préstamo
            colum = jtablaPrestamo.getColumnModel().getColumn(columna);
            String smeses = (String)colum.getHeaderValue();
            smeses = smeses.substring(0, smeses.indexOf(' '));
            meses = Integer.parseInt(smeses) * P;
            
            // Calcular la cantidad a pagar mensualmente
            if (interes == 0.0)
                pagoMensualLocal = credito / meses;
            else
                pagoMensualLocal = credito * (interes / (1 - (1 /
                        (Math.pow(1.0+interes, (double)meses)))));
                        
            // Ponerla en la tabla (se redondea a dos decimales)
            jtablaPrestamo.setValueAt(AlinDer("###,###,##0.00",
                    pagoMensualLocal), fila, columna);
        }
    }
    tablaPagos = true;

}
    private String AlinDer(String patron, double valor)
{
    java.text.DecimalFormat formato = new java.text.DecimalFormat(patron);
    String salida = formato.format(valor);
    StringBuilder espacio = new StringBuilder();
    int n = 14 - salida.length();
    for (int i = 0; i < n; i++) espacio.append(" ");
    return espacio.toString() + salida;

    }//GEN-LAST:event_jbtCalculoPagosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jbtCalculoAmortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalculoAmortActionPerformed
    javax.swing.JTable jtablaPrestamo = jTable1;
    javax.swing.JTable jtablaCabTabla = jTable1;

        // Si la tabla de pagos no ha sido calculada, no se puede amortizar
    if (!tablaPagos) return;
    
    // Obtener la fila seleccionada
    int fila = jtablaPrestamo.getSelectedRow();
    if (fila == -1) fila = 0;
    
    // Obtener la columna seleccionada
    int columna = jtablaPrestamo.getSelectedColumn();
    if (columna == -1) columna = 0;
    
    // Obtener el pago mensual de la celda elegida
    String spagoMensual = jtablaPrestamo.getValueAt(fila, columna).toString();
    spagoMensual = spagoMensual.replace(".", "");
    spagoMensual = spagoMensual.replace(',', '.');
    pagoMensual = Double.parseDouble(spagoMensual);
    
    // Obtener el tipo de interés de la cabecera de la fila actual
    String sinteres = jtablaCabTabla.getValueAt(fila, 0).toString();
    sinteres = sinteres.substring(0, sinteres.indexOf('%'));
    sinteres = sinteres.replace(',', '.');
    double interes = Double.parseDouble(sinteres) / 100 / 12;
    
    // Obtener los períodos ¿en qué vienen dados? ¿En años o en meses?
    int P = 0;
    if (!jmiAños.isEnabled())
        P = 12; // son años
    else
        P = 1; // son meses
        
    // Obtener la duración del préstamo de la cabecera de la columna actual
    javax.swing.table.TableColumn colum = jtablaPrestamo.getColumnModel().getColumn(columna);
    String smeses = (String)colum.getHeaderValue();
    smeses = smeses.substring(0, smeses.indexOf(' '));
    int meses = Integer.parseInt(smeses) * P;
    
    

    }//GEN-LAST:event_jbtCalculoAmortActionPerformed

 private void initTabla(final int filasTabla, final int colsTabla)
{
    CModeloTablaPrestamo modeloTabla = new CModeloTablaPrestamo(filasTabla, colsTabla);
    jTable1.setModel(modeloTabla);
    
   
    
    jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    jTable1.setFont(new java.awt.Font("Courier New", 0, 12));
    
    jscrollPanel.setViewportView(jTable1);
    
        // Forzar a que las columnas de dinero tengan un ancho adecuado
    for(int i = 0; i < jTable1.getColumnCount(); i++)
    {
        jTable1.getColumnModel().getColumn(i).setPreferredWidth(150);
    }

}



    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Prestamo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtCalculoAmort;
    private javax.swing.JButton jbtCalculoPagos;
    private javax.swing.JComboBox<String> jcbIncremento;
    private javax.swing.JTextField jftCredito;
    private javax.swing.JTextField jftInteresMax;
    private javax.swing.JTextField jftInteresMin;
    private javax.swing.JTextField jftPeriodoMax;
    private javax.swing.JTextField jftPeriodoMin;
    private javax.swing.JMenuItem jmiAcercaDe;
    private javax.swing.JRadioButtonMenuItem jmiAños;
    private javax.swing.JMenuItem jmiInstrucciones;
    private javax.swing.JRadioButtonMenuItem jmiMeses;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JScrollPane jscrollPanel;
    // End of variables declaration//GEN-END:variables
}
